platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.6'

inputs:
- name: omgfruitapi
  path: go/src/github.com/jwfriese/omgfruitapi

run:
  path: go/src/github.com/jwfriese/omgfruitapi/test.sh

